routes/web.php
<?php

Auth::routes();

Route::group(['namespace' => 'Front'],function() {

	Route::get('banner2',function(){
		return view('front.banner.index');
	});

	Route::get('banner',function(){
		return view('front.banner.index');
	});

	Route::get('/', ['as' => 'main','middleware' => 'checkClient','uses' => 'MainController@index']);
	Route::get('/ios', ['middleware' => 'isIos','as' => 'main.ios','uses' => 'MainController@ios']);
	Route::get('/android', ['middleware' => 'isAndroid','as' => 'main.android','uses' => 'MainController@android']);

});

Route::group(['middleware' => ['auth'], 'namespace' => 'Admin'],function() {

    Route::post('key/{id}','VersionControlController@key');
    Route::post('option/{id}','VersionControlController@option');
	Route::get('info','OlimpInfoController@index');
	Route::get('version/copy/{id}','VersionControlController@copyParams');
    Route::post('tabs_ajax_countries', 'VersionControlController@tabs_ajax_countries')->name('tabs_ajax_countries');
    Route::post('tabs_ajax', 'VersionControlController@tabs_ajax')->name('tabs-ajax');
	Route::get('users-activity-ajax', 'UsersActivityController@ajax')->name('users-activity-ajax');
	Route::get('users-activity','UsersActivityController@index')->name('users-activity');
	Route::get('load-users','UsersActivityController@loadUsers');
	Route::resource('version', 'VersionControlController');
	Route::resource('androidVersion', 'AndroidVersionController');
});

Route::group(['namespace' => 'Auth'], function() {

	Route::get('/','LoginController@showLoginForm');
});

app/Models/Version.php
<?php

namespace App\Models;

use App\Traits\UploadThumb;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Version extends Model
{
	use SoftDeletes, UploadThumb;

    protected $fillable = ['name', 'active', 'bundle_id', 'last_version', 'app_link','message_rus','message_eng', 'hidden', 'description', 'api_url', 'disallow_payments'];

	public static function boot()
	{
		parent::boot();

		static::deleted(function($version){

			$versions = $version->params()->get();
			$image = $version->thumb()->first();
			if(count($versions) > 0){
				foreach ($versions as $version){
					$version->delete();
				}
			}
			if($image){
				$image->delete();
			}
		});
	}

	public function thumb($type = null)
	{
		return $this->morphOne(Image::class, 'imageable');
	}

    public function image()
    {
        return $this->belongsTo('App\Models\Image');
    }

    public function params()
    {
    	return $this->hasMany(Params::class);
    }

    public function countries()
    {
    	return $this->belongsToMany(Country::class);
    }
}

resources/views/admin/version/index.blade.php
@extends('admin.layouts.app')

@section('title')
    Список версий
@stop

@section('content')

    @include("admin.layouts._main.header")

        <div class="content" style="margin: 10px;">
            <div class="row">
                <div class="col-lg-12 col-md-12">

                    <a class='btn btn-default pull-right' href="#myModal" style="float: left;" data-toggle="modal">Создать версию</a>

                    @include('admin.version.modal1')
                    @include('admin.version.modal2')

                    @include('admin.version.table')

                </div>
            </div>
        </div>

    @include("admin.layouts._main.footer")

@endsection

@section('scripts')
    @parent

    <script src="{{ asset('custom/js/dataTable.js') }}"></script>
    <script src="{{ asset('ace/js/duallistbox/ace.js') }}"></script>
    <script src="{{ asset('ace/js/duallistbox/elements.fileinput.js') }}"></script>
    <script src="{{ asset('ace/js/duallistbox/create.js') }}"></script>
    <script src="{{ asset('custom/duallistbox/dualbox_modal.js') }}"></script>

    <script>
        loadScript(('/smartadmin/js/table/jquery.dataTables.min.js'), function(){
            loadScript(("/smartadmin/js/table/dataTables.colVis.min.js"), function(){
                loadScript(("/smartadmin/js/table/dataTables.tableTools.min.js"), function(){
                    loadScript(("/smartadmin/js/table/dataTables.bootstrap.min.js"), function(){
                        loadScript(("/smartadmin/js/table/datatables.responsive.min.js"), pagefunction)
                    });
                });
            });
        });
    </script>

    <script>

        function new_tabs() {

            var ajax_countries = [];

            $.each($('#dual option:selected'), function(index, value) {
                ajax_countries.push({ index : value['value']});

            });
            console.log($('#id_option_tab').val());
            var id_tabs = document.getElementById('id_tabs');
            var id_tabs_var = id_tabs.value;

            var token = $('#token').attr('content');


            $.ajax({
                url: '{{ route('tabs-ajax') }}',
                type: 'post',
                data: {
                    'num_countries' : ajax_countries,
                    'name_tabs' : id_tabs_var,
                    '_token' : token
                },
                success: function (data) {
                    $('#id_tabs').val('');

                    var option_html = '<option id="id_option_tab" value="' + id_tabs_var + '">' + id_tabs_var + '</option>';
                    $('#id_select_tab').append(option_html);
                }
            });
        }
    </script>

    <script>

        $('#id_select_tab').change(function(){
            $('#show_countries').remove();

            var name_tab = $(this).val();
            var token = $('#token').attr('content');



            $.ajax({
                url: '{{ route('tabs_ajax_countries') }}',
                type: 'post',
                data: {
                    'name_tab' : name_tab,
                    '_token' : token
                },
                success: function (data) {

                    $.each($('#dual .dualclass'), function(index, value) {
                        data.db.forEach(function (element) {
                            if (element['name'] == value['value']) {
                                $('#downlist').append('<div id="show_countries"></div>')
                                $('#show_countries').append('<ul><li>' + $(value).text() + '</li></ul>');
                            }
                        })
                    });
                    $('#show_countries').append('<a onclick="change_countries_tabs();" href="javascript:void(0)">Активировать</a>');

                }
            });
        });

    </script>

    <script>

        function change_countries_tabs() {
            $.each($('#dual option:selected'), function(index, value) {
                $('.dualclass').attr('selected', false);
            });
            $('.demo2').bootstrapDualListbox('refresh');
            console.log($('#dual option:selected').text());

            var name_tab = $('#id_select_tab').val();
            var token = $('#token').attr('content');

            $.ajax({
                url: '{{ route('tabs_ajax_countries') }}',
                type: 'post',
                data: {
                    'name_tab' : name_tab,
                    '_token' : token
                },
                success: function (data) {
                    $.each($('#dual option:selected'), function(index, value) {
                        $('.dualclass').attr('selected', false);
                    });
                    $.each($('#dual .dualclass'), function(index, value) {
                        data.db.forEach(function (element) {
                            if (element['name'] == value['value']) {
                                $(value).attr('selected', 'selected');
                            } else {
                                $.each($('#dual option:selected'), function(index, value) {
                                    $('.dualclass').attr('selected', false);
                                });
                                $(value).attr('selected', 'selected');
                            }
                        })
                    });
                    $('.demo2').bootstrapDualListbox('refresh');
                }
            });
        }

    </script>

    <script>

        $('a[name=downlist]').click(function(){
            $('#downlist').slideToggle(500);
        });

    </script>

    <script>
        // дуалбокс модал 1
        var modal1 = $('.modal1').bootstrapDualListbox({
            preserveSelectionOnMove: 'moved',
            moveOnSelect: true
        });
    </script>

    <script>
        function delete_tabs() {
            $.each($('#dual option:selected'), function(index, value) {
                $('.dualclass').attr('selected', false);
            });
            $('.demo2').bootstrapDualListbox('refresh');
        }
    </script>
@endsection

resources/views/admin/version/modal1.blade.php
<div id="myModal" class="modal fade">
    <div class="container">
        <div class="row">

            <div id="modal" class="col-lg-12"><br>

                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4>Создать версию</h4>
                <hr>
                <form action="{{route('version.store')}}" method="post" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="row">

                        <!-- Первый столбик -->
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group{{ $errors->has('bundle_id') ? ' has-error' : '' }}">
                                <label>Bundle ID</label>
                                <input type="text" name="bundle_id" placeholder="bundle_id" class="form-control" value="{{ old('bundle_id') }}" autofocus required>
                                @if ($errors->has('bundle_id'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('bundle_id') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label>Название App</label>
                                <input type="text" name="name" placeholder="OLIMP Цупис" class="form-control" value="No Name">
                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('name') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('last_version') ? ' has-error' : '' }}">
                                <label>Последняя версия</label>
                                <input type="text" name="last_version" placeholder="3.2.1" class="form-control" value="1.2.3">
                                @if ($errors->has('last_version'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('last_version') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('api_url') ? ' has-error' : '' }}">
                                <label>Api адрес</label>
                                <input type="text" name="api_url" placeholder="https://api2.olimpapp.xyz:5500/api/" class="form-control">
                                @if ($errors->has('api_url'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('api_url') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('app_link') ? ' has-error' : '' }}">
                                <label>App Link</label>
                                <input type="text" name="app_link" placeholder="http://ya.ru" class="form-control" required>
                                @if ($errors->has('app_link'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('app_link') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>


                            <!-- ДУАЛЛИСТБОКС -->

                            <div class="form-group">
                                <div class="wrapp-dual{{ $errors->has('allow_countries') ? ' has-error' : '' }}">
                                    <label>Доступные страны</label>
                                    <select multiple="multiple" size="10" name="allow_countries[]" id="demo2" class="modal1">
                                        @foreach($countries as $country)
                                            <option value="{{$country->id}}">{{$country->name}} ({{$country->iso_code_2}})</option>
                                        @endforeach
                                    </select>
                                    <div class="err_dual"></div>
                                    @if ($errors->has('allow_countries'))
                                        <span class="help-block">
                                            <strong>
                                                <small>{{ $errors->first('allow_countries') }}</small>
                                            </strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <!-- ДУАЛЛИСТБОКС -->


                        </div>

                        <!-- Второй столбик -->
                        <div class="col-lg-6 col-md-6">
                            <div class="row">
                                <br>

                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-center">
                                    <div class="form-group{{ $errors->has('active') ? ' has-error' : '' }}">
                                        <div class="checkbox">
                                            <label>
                                                <input name="active" type="checkbox" class="ace" checked>
                                                <span class="lbl">Активна</span>
                                            </label>
                                        </div>
                                        @if ($errors->has('active'))
                                            <span class="help-block">
                                                <strong>
                                                    <small>{{ $errors->first('active') }}</small>
                                                </strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-center" style="margin-top: 9px;">
                                    <div class="form-group{{ $errors->has('hidden') ? ' has-error' : '' }}">
                                        <div class="checkbox">
                                            <label>
                                                <input name="hidden" type="checkbox" class="ace">
                                                <span class="lbl"> Hidden</span>
                                            </label>
                                        </div>
                                        @if ($errors->has('hidden'))
                                            <span class="help-block">
                                                <strong>
                                                    <small>{{ $errors->first('hidden') }}</small>
                                                </strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="form-group{{ $errors->has('message_eng') ? ' has-error' : '' }}">
                                <label>Сообщение на английском</label>
                                <input class="form-control" name="message_eng" value="The version of your application is not actual. Please update to the latest version.">
                                @if ($errors->has('message_eng'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('message_eng') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('message_rus') ? ' has-error' : '' }}">
                                <label>Сообщение на русском</label>
                                <input class="form-control" name="message_rus" value="Вышла новая версия. Пожалуйста, обновите приложение.">
                                @if ($errors->has('message_rus'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('message_rus') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label>Описание</label>
                                <input class="form-control" name="description" placeholder="description" required>
                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('description') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('disallow_payments') ? ' has-error' : '' }}">
                                <label>Disallow payments</label>
                                <textarea class="form-control" name="disallow_payments" placeholder="disallow_payments"></textarea>
                                @if ($errors->has('disallow_payments'))
                                    <span class="help-block">
                                        <strong>
                                            <small>{{ $errors->first('disallow_payments') }}</small>
                                        </strong>
                                    </span>
                                @endif
                            </div>

                            <div class="row">
                                <div class="col-xs-12" style="margin-top: 26px;">
                                    <a class="btn btn-default active"class="btn btn-default active" href="javascript:void(0)" id="addParams">Добавить параметр</a>
                                </div>
                            </div>
                            <br>
                            <div class="wrapper-params-action"></div>

                        </div>
                    </div>
                    <div class="text-right">
                        <button class="btn btn-primary  btn-block">Создать версию</button>
                    </div>
                    <br>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- end -->

resources/views/admin/version/table.blade.php
<table id="dt_basic" class="table table-striped table-bordered table-hover" width="100%">
    <thead>
    <tr>
        <th data-hide="phone">ID</th>

        <th data-class="expand">App name</th>
        <th>Bundle id</th>
        <th data-hide="phone">Latest version</th>
    </tr>
    </thead>
    <tbody>

    @forelse($versions as $version)

        <tr>
            <td>{{$version->id}}</td>
            @if($version->active)
                <td><a id="link_mymodal2" class="link_mymodal2"

                       data-id="{{$version->id}}"
                       data-name="{{$version->name}}"
                       data-app_link="{{$version->app_link}}"
                       data-bundle_id="{{$version->bundle_id}}"
                       data-last_version="{{$version->last_version}}"
                       data-api_url="{{$version->api_url}}"
                       data-message_eng="{{$version->message_eng}}"
                       data-message_rus="{{$version->message_rus}}"
                       data-disallow_payments="{{$version->disallow_payments}}"
                       data-active="{{$version->active}}"
                       data-allow_countries="{{$version->countries}}"
                       data-hidden="{{$version->hidden}}"
                       data-description="{{$version->description}}">

                        {{$version->name}}
                    </a><i style="float: right;" class="fa fa-circle txt-color-green" aria-hidden="true"></i></td>
            @else
                <td><a id="link_mymodal2" class="link_mymodal2"


                       data-id="{{$version->id}}"
                       data-name="{{$version->name}}"
                       data-bundle_id="{{$version->bundle_id}}"
                       data-last_version="{{$version->last_version}}"
                       data-app_link="{{$version->app_link}}"
                       data-api_url="{{$version->api_url}}"
                       data-message_eng="{{$version->message_eng}}"
                       data-message_rus="{{$version->message_rus}}"
                       data-active="{{$version->active}}"
                       data-allow_countries="{{$version->countries}}"
                       data-hidden="{{$version->hidden}}"
                       data-disallow_payments="{{$version->disallow_payments}}"
                       data-description="{{$version->description}}">

                        {{$version->name}}
                    </a><i style="float: right;" class="fa fa-circle txt-color-red" aria-hidden="true"></i></td>
            @endif
            <td>{{$version->bundle_id}}</a></td>
            <td>{{$version->last_version}}</td>

        </tr>
    @empty
        <tr>
            <td colspan="5" class="text-center">Empty</td>
        </tr>

    @endforelse
    </tbody>
</table>