routes/web.php
<?php

Auth::routes();

Route::group(['namespace' => 'Front'],function() {

	Route::get('banner2',function(){
		return view('front.banner.index');
	});

	Route::get('banner',function(){
		return view('front.banner.index');
	});

	Route::get('/', ['as' => 'main','middleware' => 'checkClient','uses' => 'MainController@index']);
	Route::get('/ios', ['middleware' => 'isIos','as' => 'main.ios','uses' => 'MainController@ios']);
	Route::get('/android', ['middleware' => 'isAndroid','as' => 'main.android','uses' => 'MainController@android']);

});

Route::group(['middleware' => ['auth'], 'namespace' => 'Admin'],function() {

    Route::post('key/{id}','VersionControlController@key');
    Route::post('option/{id}','VersionControlController@option');
	Route::get('info','OlimpInfoController@index');
	Route::get('version/copy/{id}','VersionControlController@copyParams');
    Route::post('tabs_ajax_countries', 'VersionControlController@tabs_ajax_countries')->name('tabs_ajax_countries');
    Route::post('tabs_ajax', 'VersionControlController@tabs_ajax')->name('tabs-ajax');
	Route::get('users-activity-ajax', 'UsersActivityController@ajax')->name('users-activity-ajax');
	Route::get('users-activity','UsersActivityController@index')->name('users-activity');
	Route::get('load-users','UsersActivityController@loadUsers');
	Route::resource('version', 'VersionControlController');
	Route::resource('androidVersion', 'AndroidVersionController');
});

Route::group(['namespace' => 'Auth'], function() {

	Route::get('/','LoginController@showLoginForm');
});

app/Http/Controllers/Front/MainController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\AndroidVersion;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Version;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client;

class MainController extends Controller
{
    public function index(Request $request)
    {
        $versions = Version::where('hidden',0)->paginate(8);
	    $androidVersions = $this->getAndroidLink();
        //$androidVersions = AndroidVersion::where('hidden',0)->paginate(8);
	    $active = 'ios';
	    if(isset($request->active)){
		    $active = $request->active;
	    }

	    $secret_parameter = '7ba2ff57702c100155220398731e9504gdms0524';
	    $check_param = $request->input('secret_key', false);

	    if ($check_param && $secret_parameter == $check_param) {
            return view('front.main.index', ['versions' => $versions, 'androidVersions' => $androidVersions, 'active' => $active]);
        } else {
            return view('front.main.empty', ['versions' => $versions, 'androidVersions' => $androidVersions, 'active' => $active]);
        }
    }

    public function ios()
    {
	    $versions = Version::where('hidden',0)->paginate(8);
	    return view('front.main.ios',['versions' => $versions]);
    }

	public function android()
	{
		$versions = AndroidVersion::where('hidden',0)->paginate(8);
		return view('front.main.android',['versions' => $versions]);
	}

	protected function getAndroidLink()
	{
		$client = new Client();
		$res = $client->request('GET', 'http://olimpcasino.bid/last/info/');
		$data = json_decode($res->getBody(),true);
		foreach ($data['links'] as &$link){
			$link = base64_decode($link);
		}
		return $data;
	}
}

resources/views/admin/layouts/_main/header.blade.php
<header id="header">
    <div id="logo-group">
        <span id="logo"> <img src="/smartadmin/img/logo.png" alt="SmartAdmin"> </span>
    </div>
    @if (Auth::guest())
    @else
            <div id="left_menu" class="pull-left" style="margin-top: 10px;">
                <a class="btn btn-default {{(Request::path()=='version')?'active':''}}" href="{{route('version.index')}}">Версии</a>
                <a class="btn btn-default {{(Request::path()=='users-activity')?'active':''}}" href="{{route('users-activity')}}">Пользователи</a>
            </div>

            <div id="right_menu" class="pull-right" style="margin-top: 10px;">
                <a class="btn btn-default" style="width: 100% !important;" href="{{ route('logout') }}"onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Выйти</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </div>
            <div id="menu" class="pull-right" style="margin-top: 10px;">
                <a href="#" class="menu-trigger">Меню</a>
            </div>

            <div id="toogle_menu" class="pull-right" style="margin-top: 10px;">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="javascript:void(0);">Меню</a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{route('version.index')}}" style="width: 100% !important;">Версии</a>
                        </li>
                        <li>
                            <a href="{{route('users-activity')}}" style="width: 100% !important;">Пользователи</a>
                        </li>
                        <li>
                            <a style="width: 100% !important;" href="{{ route('logout') }}"onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Выйти</a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
            </div>
    @endif
    <style>
        .btn-default.active {
            background: #991b1c !important;
            color: white;
        }
    </style>

</header>

resources/views/admin/layouts/_main/leftmenu.blade.php
<ul class="nav nav-list" style="top: 0px;">
    <li class="@if($active=='ios') active  @endif">
        <a href="/version" class="dropdown-toggle">
            <i class="menu-icon fa fa-server"></i>
            <span class="menu-text">Версии</span>
        </a>
    </li>
    <li class="@if($active=='user_activity') active  @endif">
        <a href="/users-activity" class="dropdown-toggle">
            <i class="menu-icon fa fa-user"></i>
            <span class="menu-text">Пользователи</span>
        </a>
    </li>
</ul>